services:
  - type: static_site
    name: carelink-web
    buildCommand: |
      git clone https://github.com/flutter/flutter.git -b stable
      export PATH="$PATH:./flutter/bin"
      flutter config --enable-web
      flutter pub get
      flutter build web
    publishPath: build/web
