// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-F_DbQJGA4dL13faMv94HwaXqdURpGJc',
    appId: '1:460843315926:web:f14f8f7b21e3eaa9d08f77',
    messagingSenderId: '460843315926',
    projectId: 'sentinel-b5582',
    authDomain: 'sentinel-b5582.firebaseapp.com',
    storageBucket: 'sentinel-b5582.firebasestorage.app',
    measurementId: 'G-9NDPGB9N8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVh0KcoRxZCS0khqmgxUzB1X0UHzjehpE',
    appId: '1:460843315926:android:bef8c7ae685f3d46d08f77',
    messagingSenderId: '460843315926',
    projectId: 'sentinel-b5582',
    storageBucket: 'sentinel-b5582.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4BJdDeqGbw9NduJ2EXQmOy6k-pRUcSAY',
    appId: '1:460843315926:ios:e1885c8cab811143d08f77',
    messagingSenderId: '460843315926',
    projectId: 'sentinel-b5582',
    storageBucket: 'sentinel-b5582.firebasestorage.app',
    iosBundleId: 'com.example.alerta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-F_DbQJGA4dL13faMv94HwaXqdURpGJc',
    appId: '1:460843315926:web:fb353cd87a879244d08f77',
    messagingSenderId: '460843315926',
    projectId: 'sentinel-b5582',
    authDomain: 'sentinel-b5582.firebaseapp.com',
    storageBucket: 'sentinel-b5582.firebasestorage.app',
    measurementId: 'G-TZCYK6RB4T',
  );
}
